import './globals.css';

import { Lato, Roboto, Montserrat} from 'next/font/google';

import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import GlobalState from '@/context';


export const roboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-lato',
})

export const montserrat = Montserrat({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'E-Shop, votre boutique en ligne',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${roboto.variable} ${lato.variable} ${montserrat.variable} font-montserrat`}>
        <GlobalState>
          <Navbar />
          <main className='flex min-h-screen flex-col mt-0'>
            {children}
          </main>
          <Footer />
        </GlobalState>
      </body>
    </html>
  )
};
